GET http://localhost:20052/player/getAll HTTP/1.1

###

GET http://localhost:20052/player/getOneById/2 HTTP/1.1

#enrique@gmail.com
###
GET http://localhost:20052/player/getOneByEmail/enrique@gmail.com HTTP/1.1

###
POST http://localhost:20052/player/createOnePlayer HTTP/1.1
content-type: application/json

{
    "name": "Skarlet",
    "email": "Skarlett@gmail.com",
    "password": "123asdasd",
    "nickname": "Skarlettt",
    "bithday": "2004-07-22T00:00:00.000Z",
    "portrait_img": "aasdaq1313asdasdasd"
}

###
PUT http://localhost:20052/player/updatePlayer/95 HTTP/1.1
content-type: application/json

{
    "name": "Skarlet",
    "email": "Shjktjjjt@gmail.com",
    "password": "123asdasd",
    "nickname": "frlehhttt",
    "bithday": "2004-07-22T00:00:00.000Z",
    "portrait_img": "aasdaq1313asdasdasd",
    "Estatus": false
}

###
DELETE http://localhost:20052/player/delPlayer/1 HTTP/1.1

###
PATCH http://localhost:20052/player/patchPlayer/5 HTTP/1.1







###

GET http://localhost:20052/partida/getAll HTTP/1.1

###

GET http://localhost:20052/partida/getOneById/2 HTTP/1.1

#enrique@gmail.com
###
GET http://localhost:20052/partida/getOneByIdPlayer/2 HTTP/1.1

###
POST http://localhost:20052/partida/createOnePartida HTTP/1.1
content-type: application/json

{
    "idPlayer": "1",
    "level": "1",
    "startGame": "00:00:00",
    "endGame": "00:22:00",
    "score_st": 0.0,
    "score_end": 128.0,
    "previos_game_leve_ID": 1
}

###
PUT http://localhost:20052/partida/updatePartida/2 HTTP/1.1
content-type: application/json

{
    "idPlayer": "1",
    "level": "1",
    "startGame": "00:00:00",
    "endGame": "00:44:00",
    "score_st": 0.0,
    "score_end": 123.0,
    "previos_game_leve_ID": 1,
    "Estatus": false
}

###
DELETE http://localhost:20052/partida/delPartida/1 HTTP/1.1

###
PATCH http://localhost:20052/partida/patchPartida/2 HTTP/1.1
